# Generated by Django 5.0.4 on 2024-07-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="host",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(default="", max_length=8, unique=True),
        ),
    ]
