# Generated by Django 5.0.4 on 2024-07-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_room_host_alter_room_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=50, unique=True)),
                ("password", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
